export enum ActionTypes {
  // Status
  LOADED = "LOADED",
  NOT_LOADED = "NOT_LOADED",
  IS_LOADING = "IS_LOADING",
  LOADING_FAILED = "LOADING_FAILED",

  // Fetch all logs
  FETCH_LOGS_LOADING = "FETCH_LOGS_LOADING",
  FETCH_LOGS = "FETCH_LOGS",
  FETCH_LOGS_SUCCESS = "FETCH_LOGS_SUCCESS",
  FETCH_LOGS_ERROR = "FETCH_LOGS_ERROR",
  
  // Fetch loans
  FETCH_LOANS_LOADING = "FETCH_LOANS_LOADING",
  FETCH_LOANS = "FETCH_LOANS",
  FETCH_LOANS_SUCCESS = "FETCH_LOANS_SUCCESS",
  FETCH_LOANS_ERROR = "FETCH_LOANS_ERROR",
}
